In [2]:
import pandas as pd

**Abbrivations**:
> cbs = crime by state
> 
> cbd = crime by district

In [3]:
cbd = pd.read_csv(".././datasets/crime_by_district_rt.csv")
cbd

,STATE/UT,DISTRICT,Year,Murder,Assault on women,Kidnapping and Abduction,Dacoity,Robbery,Arson,Hurt,Prevention of atrocities (POA) Act,Protection of Civil Rights (PCR) Act,Other Crimes Against SCs
0,ANDHRA PRADESH,ADILABAD,2001,0,1,4,0,0,0,3,0,15,32
1,ANDHRA PRADESH,ANANTAPUR,2001,0,4,0,0,0,0,49,21,0,53
2,ANDHRA PRADESH,CHITTOOR,2001,3,3,0,0,0,0,38,36,0,34
3,ANDHRA PRADESH,CUDDAPAH,2001,0,3,0,0,0,0,20,52,0,25
4,ANDHRA PRADESH,EAST GODAVARI,2001,1,3,0,0,0,0,3,12,63,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9380,Delhi UT,STF,2013,0,0,0,0,0,0,0,0,0,0
9381,Delhi UT,WEST,2013,0,0,0,0,0,0,0,3,1,0
9382,Lakshadweep,LAKSHADWEEP,2013,0,0,0,0,0,0,0,0,0,0
9383,Puducherry,KARAIKAL,2013,0,1,0,0,0,0,0,0,3,0
9384,Puducherry,PUDUCHERRY,2013,0,0,0,0,0,0,0,4,12,1